CodersMVCProject/Models/ErrorViewModel.cs
namespace CodersMVCProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CodersMVCProject/Models/Product.cs
using System.ComponentModel;

namespace CodersMVCProject.Models;

public class Product
{
    public int Id { get; set; }
    [DisplayName("Title")]
    public string Name { get; set; }
    public decimal Price { get; set; }
}

CodersMVCProject/Controllers/HomeController.cs
using CodersMVCProject.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CodersMVCProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CodersMVCProject/Controllers/ProductsController.cs
using CodersMVCProject.Models;
using Microsoft.AspNetCore.Mvc;

namespace CodersMVCProject.Controllers
{
    public class ProductsController : Controller
    {
        private readonly static List<Product> products = new List<Product>
    {
        new Product { Id = 1, Name = "Keyboard", Price = 20 },
        new Product { Id = 2, Name = "Mouse", Price = 10 },
        new Product { Id = 3, Name = "Monitor", Price = 100 }
    };

        public IActionResult Index()
        {
            return View(products);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Product product)
        {
            product.Id = products.Count + 1;
            products.Add(product);
            return RedirectToAction("Index");
        }
    }
}

CodersMVCProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CodersMVCProject/Views/Products/Add.cshtml
@model Product

<h2>Add New Product</h2>


<form asp-controller="Products" asp-action="Add">
    <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="Product name" aria-label="Name" aria-describedby="basic-addon1" asp-for="Name" />
    </div>
    <div class="input-group mb-3">
        <input type="text" placeholder="Price" class="form-control" aria-label="Amount" asp-for="Price" />
    </div>
    <button type="submit" asp-controller="Products" asp-action="Add" class="btn btn-primary">Add Product</button>
</form>

@* @model Product

<h2>Add New Product</h2>

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Price)
        @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-primary">Add Product</button>
}
 *@

CodersMVCProject/Views/Products/Index.cshtml
@model List<Product>

<h2>Products List</h2>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model)
        {
            <tr>
                <td>@product.Id</td>
                <td>@product.Name</td>
                <td>@product.Price</td>
            </tr>
        }
    </tbody>
</table>

<a type="button" asp-controller="Products" asp-action="Add" class="btn btn-primary">Add Product</a>

CodersMVCProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductMVC2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductMVC2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProductMVC2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy;@DateTime.Now.ToString("G")  - Product2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>